version: '3.5' 
services: 
   keycloak:
      container_name: keycloackcontainer
      build: ./keycloak
      ports:
        - 8080:8080
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
      command:
        - start-dev  
   angular-service: # The name of the service
      container_name: angularcontainer  # Container name
      build: ./ # Location of our Dockerfile
      volumes: # Volume binding
        - './Scrumboard:/src/usr/app' 
      ports:
        - 4200:4200
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0"
   nodejs-service:
      container_name: nodecontainer
      build: ./nodejs_backend
      ports:
        - 3000:3000
   opa:
    container_name: opaserver
    image: openpolicyagent/opa:latest
    ports:
    - 8181:8181
    # WARNING: OPA is NOT running with an authorization policy configured. This
    # means that clients can read and write policies in OPA. If you are
    # deploying OPA in an insecure environment, be sure to configure
    # authentication and authorization on the daemon. See the Security page for
    # details: https://www.openpolicyagent.org/docs/security.html.
    command:
    - "run"
    - "--server"
    - "--log-level=debug"
    - "--log-format=json-pretty"
    - "./policy.rego"
    volumes:
      - ./keycloak/policy.rego:/policy.rego
